[package]
name = "wleave"
version = "0.3.2"
edition = "2021"
license = "MIT"
description = "A Wayland-native logout script written in Gtk3"
repository = "https://github.com/AMNatty/wleave"

[workspace]
members = [".", "completions_gen"]

[dependencies]
clap = { version = "4.1", features = ["derive"] }

dirs = "5.0"
gtk = "0.18"
gtk-layer-shell = "0.8"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
